CSRazorSolution/WebApp/Pages/Samples/BasicDataManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Samples
{
    public class BasicDataManagementModel : PageModel
    {
        //create bound properties that are directly tied to a control on the form
        //bound properties have the data automatically transferred from the control
        //      into the property
        [BindProperty]
        public int Num { get; set; } //this is tied to the control using the asp-for
        [BindProperty]
        public string FavouriteCourse { get; set; }
        [BindProperty]
        public string Comments { get; set; }

        //Annotation TempData is required IF you are processing multiple requests
        //      (OnPost followed by OnGet) to retain data within the property
        //[TempData]
        public string Feedback { get; set; }
        public void OnGet()
        {
            //executes for a Get request
            //the first time the page is requested an automatic Get request is sent
            //excellent "event" to use to do any initialization to your web page display
            //      as the page is shown for the first time
        }

        public void OnPost()
        {
            //processes the OnPost request of the form (method="post")
            //the returndatatype can be void or IActionResult
            //OnPost request is the request from a <button> that has NOT indicated a
            //      specific process Post using the asp-page-handler
            //logic that you wish to accomplish should be isolated to the actions
            //  desired for the button
            Feedback = $"Number {Num}, Course {FavouriteCourse}, Comments {Comments}";
        }

        public void OnPostA()
        {
            //processes the OnPost request of the form (method="post")
            //this method is called due to the helper-tag on the form button
            //the "string" used on the helper-tag asp-page-handler="string" is
            //  added to the OnPost method name
            Feedback = $"Button A was pressed";
        }

        public void OnPostB()
        {
            //processes the OnPost request of the form (method="post")
            //this method is called due to the helper-tag on the form button
            //the "string" used on the helper-tag asp-page-handler="string" is
            //  added to the OnPost method name
            Feedback = $"Button B was pressed";
        }
    }
}

CSRazorSolution/WebApp/Pages/Samples/CategoryProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;       //this is where the services were coded
using WestWindSystem.Entities;  //this is where the entity definition is coded
using WebApp.Helpers;           //this is where the Paginator is coded
#endregion


namespace WebApp.Pages.Samples
{
    public class CategoryProductsModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly ILogger<IndexModel> _logger;
        private readonly ProductServices _productServices;
        private readonly CategoryServices _categoryServices;
        private readonly SupplierServices _supplierServices;


        public CategoryProductsModel(ILogger<IndexModel> logger,
            ProductServices productservices,
            CategoryServices categoryservices,
            SupplierServices supplierservices)
        {
            _logger = logger;
            _productServices = productservices;
            _categoryServices = categoryservices;
            _supplierServices = supplierservices;

        }
        #endregion

        [TempData]
        public string Feedback { get; set; }

        [BindProperty(SupportsGet = true)]
        public int? searcharg { get; set; }

        public List<Product> ProductInfo { get; set; }

        [BindProperty]
        public List<Category> CategoryList { get; set; } = new();

        [BindProperty]
        public List<Supplier> SupplierList { get; set; } = new();

        public void OnGet()
        {
            PopulateLists();
            if(searcharg.HasValue && searcharg.Value > 0)
            {
                ProductInfo = _productServices.Product_CategoryProducts(searcharg.Value);
            }
        }

        public void PopulateLists()
        {
            CategoryList = _categoryServices.Category_List();
            SupplierList = _supplierServices.Supplier_List();
        }

        public IActionResult OnPostFetch()
        {
            if (searcharg.Value == 0)
            {
                Feedback = "Required: Search category not selected.";
            }

            return RedirectToPage(new { searcharg = searcharg });
        }

        public IActionResult OnPostClear()
        {
            Feedback = "";
            //searcharg = null;
            ModelState.Clear();
            return RedirectToPage(new { searcharg = (int?)null });
        }

        public IActionResult OnPostNew()
        {
            return RedirectToPage("/Samples/ProductCRUD");
        }

    }
}

CSRazorSolution/WebApp/Pages/Samples/Controls.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Samples
{
    public class ControlsModel : PageModel
    {
        [TempData]
        public string Feedback { get; set; }

        [BindProperty]
        public string EmailText { get; set; }
        [BindProperty]
        public string PasswordText { get; set; }
        [BindProperty]
        public string DateTimeText { get; set; }

        [BindProperty]
        public string RadioMeal { get; set; }
        public string[] RadioMeals = new[] { "breakfast", "lunch", "dinner/supper", "snacks" };

        [BindProperty]
        public bool AcceptanceBox { get; set; } //remember value=true on input control

        [BindProperty]
        public string MessageBody { get; set; }

        [BindProperty]
        public int MyRide { get; set; }
        //pretend the collection is coming from the database
        //each row of the collection has two values: selection value; selection text
        //the class SelectionList will be use as the datatype for the collection
        public List<SelectionList> Rides { get; set; } 

        [BindProperty]
        public string VacationSpot { get; set; }
        public List<string> VacationSpotList { get; set; }

        [BindProperty]
        public int RangeValue { get; set; }
        
        public void OnGet()
        {
            PopulateLists();
        }

        public void PopulateLists()
        {
            //pretending that this data comes from the database
            Rides = new List<SelectionList>();
            Rides.Add(new SelectionList() { ValueId = 3, DisplayText="Bike" });
            Rides.Add(new SelectionList() { ValueId = 5, DisplayText="Board" });
            Rides.Add(new SelectionList() { ValueId = 2, DisplayText="Bus" });
            Rides.Add(new SelectionList() {ValueId = 1, DisplayText="Car" });
            Rides.Add(new SelectionList() { ValueId = 4, DisplayText="Motorcycle" });

            VacationSpotList = new List<string>();
            VacationSpotList.Add("California");
            VacationSpotList.Add("Caribbean");
            VacationSpotList.Add("Cruising");
            VacationSpotList.Add("Europe");
            VacationSpotList.Add("Florida");
            VacationSpotList.Add("Mexico");

        }
        public IActionResult OnPostText()
        {
            //this method is tied to the specific button on the form via
            //  the asp-page-handler attribute.
            //the form of the method name is OnPost then concatenate the
            //  value given to the handler attribute

            Feedback = $"Email {EmailText}; Password {PasswordText}; Date {DateTimeText}";
            PopulateLists();
            return Page();
        }

        public IActionResult OnPostRadioCheckArea()
        {
            Feedback = $"Meal {RadioMeal}; Acceptance {AcceptanceBox}; Message {MessageBody}";
            PopulateLists();
            return Page();
        }

        public IActionResult OnPostListSlider()
        {
            Feedback = $"Ride {MyRide}; Vacation {VacationSpot}; Review Satification {RangeValue}";
            PopulateLists();
            return Page();
        }

    }

    public class SelectionList
    {
        //common class used to hold 2 values for use in a select list scenario such
        //  as a drop down list
        public int ValueId { get; set; }
        public string DisplayText { get; set; }
    }

}

CSRazorSolution/WebApp/Pages/Samples/ProductCRUD.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;       //this is where the services were coded
using WestWindSystem.Entities;  //this is where the entity definition is coded
using WebApp.Helpers;           //this is where the Paginator is coded
#endregion


namespace WebApp.Pages.Samples
{
    public class ProductCRUDModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly ILogger<IndexModel> _logger;
        private readonly ProductServices _productServices;
        private readonly CategoryServices _categoryServices;
        private readonly SupplierServices _supplierServices;


        public ProductCRUDModel(ILogger<IndexModel> logger,
            ProductServices productservices,
            CategoryServices categoryservices,
            SupplierServices supplierservices)
        {
            _logger = logger;
            _productServices = productservices;
            _categoryServices = categoryservices;
            _supplierServices = supplierservices;

        }
        #endregion

        #region Feedback and Error Messages

        [TempData]
        public string Feedback { get; set; }

        public bool HasFeedback => !string.IsNullOrWhiteSpace(Feedback);

        public string ErrorMessage { get; set; }

        public bool HasError => !string.IsNullOrWhiteSpace(ErrorMessage);

        #endregion


        [BindProperty(SupportsGet = true)]
        public int? productid { get; set; }

        [BindProperty]
        public Product ProductInfo { get; set; }

        //adding a =new() to the List<T> declaration ensures that you have
        //  AT MINIMUM a list instance WHICH will be empty until you fill it.
        [BindProperty]
        public List<Category> CategoryList { get; set; } = new();

        [BindProperty]
        public List<Supplier> SupplierList { get; set; } = new();

        public void OnGet()
        {
            //the OnGet executes the first time the page is generated
            //then on each Get request issued by the page (such as on 
            //  RedirectToPage(),  PRG)
            PopulateLists();
            if (productid.HasValue && productid > 0)
            {
                ProductInfo = _productServices.Product_GetByID(productid.Value);
            }

        }
        public void PopulateLists()
        {
            CategoryList = _categoryServices.Category_List();
            SupplierList = _supplierServices.Supplier_List();
        }

        public IActionResult OnPostClear()
        {
            Feedback = "";
            //searcharg = null;
            ModelState.Clear();
            return RedirectToPage(new { productid = (int?)null });
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("/Samples/CategoryProducts");
        }

        public IActionResult OnPostNew()
        {
            //forces client side validation to re-execute
            if (ModelState.IsValid)
            {
                //the try/catch error handling is used to catch errors
                //  generated by the execution of the BLL service
                try
                {
                    //any BindProperty will have the current control contents
                    //  in the property
                    //if you expect to receive a value from the BLL service
                    //  you can catch the value in a local variable
                    //In our example, I am expecting the new product id to
                    //  be returned from the BLL service
                    int newproductid = _productServices.Product_AddProduct(ProductInfo);
                    //always give feedback to the client user
                    Feedback = $"Product id ({newproductid}) has been added to the system.";
                    //return needed due to IActionResult
                    return RedirectToPage(new { productid = newproductid });
                }
                catch (ArgumentNullException ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    //reload ANY lists that are being used on your form
                    //example: a list (collection) for a drop down control
                    PopulateLists();
                    //stay on the "same" page
                    //the idea is not to "leave" the current request
                    //this is required because you are using IActionResult as
                    //  a return datatype for this method
                    return Page();
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    //reload ANY lists that are being used on your form
                    //example: a list (collection) for a drop down control
                    PopulateLists();
                    //stay on the "same" page
                    //the idea is not to "leave" the current request
                    //this is required because you are using IActionResult as
                    //  a return datatype for this method
                    return Page();
                }
            }
            else
            {
                //if you are using ModelState AND are in need of re-populating
                //  lists (for select or group of radio-buttons, etc)
                //  you will need to re-obtain the lists
                PopulateLists();
            }
            return Page();
        }

        public IActionResult OnPostUpdate()
        {            
            if (ModelState.IsValid)
            {                
                try
                {                    
                    int rowaffected = _productServices.Product_UpdateProduct(ProductInfo);
                    if (rowaffected > 0)
                    {
                        Feedback = $"Product id ({rowaffected}) has been updated in the system.";
                    }

                    Feedback = "No product was affected. Refresh search and try again.";
                    
                    return RedirectToPage(new { productid = productid });
                }
                catch (ArgumentNullException ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;                    
                    PopulateLists();                    
                    return Page();
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;                   
                    PopulateLists();                  
                    return Page();
                }
            }
            else
            {
                //if you are using ModelState AND are in need of re-populating
                //  lists (for select or group of radio-buttons, etc)
                //  you will need to re-obtain the lists
                PopulateLists();
            }
            return Page();
        }

        public IActionResult OnPostDelete()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //this is a logical delete (really just update of active/inactive attribute)
                    int rowaffected = _productServices.Product_DeleteProduct(ProductInfo);
                    if (rowaffected > 0)
                    {
                        Feedback = $"Product id ({rowaffected}) has been discontinued in the system.";
                    }

                    Feedback = "No product was affected. Refresh search and try again.";

                    return RedirectToPage(new { productid = productid });
                }
                catch (ArgumentNullException ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }
            }
            else
            {
                //if you are using ModelState AND are in need of re-populating
                //  lists (for select or group of radio-buttons, etc)
                //  you will need to re-obtain the lists
                PopulateLists();
            }
            return Page();
        }

        private Exception GetInnerException(Exception ex)
        {
            //drill down to the real error message
            while (ex.InnerException != null)
            {
                ex = ex.InnerException;
            }
            return ex;
        }
    }
}

CSRazorSolution/WebApp/Pages/Samples/CategoryProducts.cshtml
@page "{searcharg?}"
@model WebApp.Pages.Samples.CategoryProductsModel
@{
    ViewData["Title"] = "Category Products";
}

<style>
   :root {
        --max-body-width: 60rem;
    }

    .setflex {
        display: flex;
    }

    .onethird{
        width: 31%;
        margin-right: 2%;
    }

    .onehalf {
        width: 47%;
        margin-right: 3%;
    }

    .smallbox {
        width: 60px;
    }
</style>

@* sample of column formatting under Holiday.css
    uses above styling
    setup 2 column Single CRUD page

    <section class="setflex">
        <div class="onehalf">
            put your query in this div
        </div>
            put your CRUD form in this div
        <div class="onehalf">
        </div>
    </section>
*@

<h1>Category Products: Select Product for Maintenance</h1>

<p>@Model.Feedback</p>

<form method="post">
    <label>
        Select a category:
        <select asp-for="searcharg">
            <option value="0">select ...</option>
            @foreach (var cat in Model.CategoryList)
            {
                <option value="@cat.CategoryID" selected=@(cat.CategoryID == Model.searcharg )>
                    @cat.CategoryName
                </option>
            }
        </select>
    </label>
    <br/>
    @*restrict the display of the table to when there is data to view*@
    @if (Model.ProductInfo != null)
    {
        if (Model.ProductInfo.Count == 0)
        {
            <p style="color:blueviolet; font-weight:bold; font-size:large;">
                There are no products matching your search request.
            </p>
        }
        else
        {
            <table>
                <thead>
                    @*used for column titles*@
                    <tr>
                        <th>Product</th>
                        <th>Supplier</th>
                        <th>Unit Size</th>
                        <th>Disc</th>
                    </tr>
                </thead>
                <tbody>
                    
                    @foreach (var item in Model.ProductInfo)
                    {
                        <tr>
                            <td>
                                <a href="/Samples/ProductCRUD/@item.ProductID">
                                    @item.ProductName
                                </a>
                            </td>
                            <td><select disabled="true">
                                    @foreach (var supplier in Model.SupplierList)
                                    {
                                        if (supplier.SupplierID == item.SupplierID)
                                        {
                                            <option value="@supplier.SupplierID" selected>@supplier.CompanyName</option>
                                        }
                                        else
                                        {
                                            <option value="@supplier.SupplierID">@supplier.CompanyName</option>
                                        }
                                    }
                                </select> 
                            </td>
                            <td>@item.QuantityPerUnit</td>
                            <td>
                                <input type="checkbox" checked="@item.Discontinued">
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                
                </tfoot>
            </table>
        }
    }
    <button type="submit" asp-page-handler="Fetch">Fetch Products</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="New" formnovalidate>New Product</button>

</form>

CSRazorSolution/WebApp/Pages/Samples/PartialFilterSearch.cshtml
@page "{searcharg?}"
@model WebApp.Pages.Samples.PartialFilterSearchModel
@{
	ViewData["Title"] = "Partial String Table Query";
}
<h1>Partial String query resulting in a Table display</h1>

<p>@Model.Feedback</p>

<form method="post">
	<label>		
		Enter a partial Territory description:
		<input type="text" asp-for="searcharg"
			placeholder="enter your description" required/>			
	</label>
	<br/>
	@*restrict the display of the table to when there is data to view*@
	@if (Model.TerritoryInfo != null)
	{
		if (Model.TerritoryInfo.Count == 0)
		{
			<p style="color:blueviolet; font-weight:bold; font-size:large;">
				There are no territories matching your search request.
			</p>
		}
		else
		{
			<table>
				<thead>
					@*used for column titles*@
					<tr>
						<th>Territory</th>
						<th>Name</th>
						<th>Region ID</th>
					</tr>
				</thead>
				<tbody>
					@*used for the table details
						the number of rows are usually unknown for a db query
					*@
					@foreach (var item in Model.TerritoryInfo)
					{
						<tr>
							<td>
							@*
								this example will send the TerritoryID to another page
								use the anchor tage to accomplish this task
								the href page value MUST be referenced from the Pages folder
								the value to be passed is attached to the end of the 
									page reference
								In this example, the value will be passed to the receiving
									page as a routing parameter
								You CAN send multiple values to the new page
								The receiving page MUST have the same number of routing parameters
									as those passed AND the order of the routing parameters
									is important
								Page reference syntax: /pathname/value[/value/...] --remember that in syntax notation [] square brakets indicate optional syntax. Do NOT include square brackets when coding
								The text of your anchor tag does NOT need to be the value
									that is being passed
							*@
							<a href="/Samples/ReceivingPage/@item.TerritoryID">
								Edit this territory
							</a>
							@item.TerritoryID
							</td>
							<td>@item.TerritoryDescription</td>
							<td><select disabled="true">
									@foreach (var region in Model.RegionList)
									{
										if (region.RegionID == item.RegionID)
										{
											<option value="@region.RegionID" selected>@region.RegionDescription</option>
										}
										else
										{
											<option value="@region.RegionID">@region.RegionDescription</option>
										}
									}
								</select>
							</td>
						</tr>
					}

				</tbody>
				<tfoot>
				@*used for summary table information eg. totals
					used for displaying paging information
				*@
					<tr>
						<td colspan="3">
							@{
								//the pageRef is the string representation of the 
								//	the value to be displayed AND its numeric
								//the string maybe a character line : Next
								//the string maybe a numeric : 4
								//	First Previous 1 2 3 4 5 Next Last
								foreach(var pageRef in Model.Pager)
								{
									if (pageRef == Model.Pager.CurrentPage)
									{
										<b>@pageRef.Text</b>
									}
									else
									{
										//create an anchor tag to move to the
										//	desired collection page
										//the target of the anchor destination
										//	is your current web cshtml
										//this will cause an OnGet issue
										// .Page is the numeric representation
										//	of the desired page
										//for the asp-page your page name reference
										//	MUST be based from the folder named Pages
										//	ie. if your page is in a subfolder, you have
										//	 to include the subfolder in the path even if
										//	you're linking to a page in the same folder
										<a title="Page @pageRef.Page"
										   asp-page="/Samples/PartialFilterSearch"
										   asp-route-currentpage="@pageRef.Page">
										   @pageRef.Text
										 </a>
									}
								}
							}
						</td>
					</tr>
				</tfoot>
			</table>
		}
	}
	<button type="submit" asp-page-handler="Fetch">Fetch Territories</button>&nbsp;&nbsp;	
	<button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
	<button type="submit" asp-page-handler="New" formnovalidate>New Territory</button>
</form>

CSRazorSolution/WebApp/Pages/Samples/ProductCRUD.cshtml
@page "{productid?}"
@model WebApp.Pages.Samples.ProductCRUDModel
@{
        ViewData["Title"] = "Product Maintenance";

}

<style>
   :root {
        --max-body-width: 60rem;
    }

    .setflex {
        display: flex;
    }

    .onethird{
        width: 31%;
        margin-right: 2%;
    }

    .onehalf {
        width: 47%;
        margin-right: 3%;
    }

    .smallbox {
        width: 60px;
    }
</style>

@*include the validation libraries on the web page
    this is done by using the RenderSection Scripts
        located on the _Layout page (at the bottom)

    RenderSections can be placed anywhere on your
        cshtml page.
*@
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

<h1>Product Maintenance: CRUD Product ID : @Model.productid</h1>

@if (Model.HasFeedback)
{
    <p>@Model.Feedback</p>
}
@if (Model.HasError)
{
    <p>@Model.ErrorMessage</p>
}

<form method="post">

    @* TODO: setup the parts of the Product*@

    @* create a control that will hold the product pkey value
        this control should NOT be changeable IF your pkey is an IDENTITY
        this control CAN be visible (type="text") or hidden (type="hidden"), which is a design consideration
    *@
    <label>
        ID:
        @if(Model.ProductInfo == null)
        {
            <input type="text" asp-for="ProductInfo.ProductID" readonly data-val="false"
            value="0"/> 
        }
        else
        {
            <input type="text" asp-for="ProductInfo.ProductID" readonly data-val="false"/>
        }
        <span asp-validation-for="ProductInfo.ProductID"></span>
    </label>
    <label>
        Name:
        <input type="text" asp-for="ProductInfo.ProductName" placeholder="product name" />
        <span asp-validation-for="ProductInfo.ProductName"></span>
    </label>
    <label>
        Category:
        <select asp-for="ProductInfo.CategoryID">
            @foreach(var item in Model.CategoryList)
            {
                <option value="@item.CategoryID" selected=@(Model.ProductInfo != null && item.CategoryID == Model.ProductInfo.CategoryID)>
                    @item.CategoryName
                </option>
            }
        </select>
        <span asp-validation-for="ProductInfo.CategoryID"></span>
    </label>
    <label>
        Supplier:
        <select asp-for="ProductInfo.SupplierID">
            @foreach(var item in Model.SupplierList)
            {
                <option value="@item.SupplierID" selected=@(Model.ProductInfo != null && item.SupplierID == Model.ProductInfo.SupplierID)>
                    @item.CompanyName
                </option>
            }
        </select>
        <span asp-validation-for="ProductInfo.SupplierID"></span>
    </label>
    <label>
        Qty Per Unit:
        <input type="text" asp-for="ProductInfo.QuantityPerUnit" placeholder="unit size" />
        <span asp-validation-for="ProductInfo.QuantityPerUnit"></span>
    </label>
    <label>
        Min Order Qty:
        <input type="number" asp-for="ProductInfo.MinimumOrderQuantity" placeholder="minimum order qty"
                step="1" min="1" />
        <span asp-validation-for="ProductInfo.MinimumOrderQuantity"></span>
    </label>
    <label>
        Unit Price:
        <input type="number" asp-for="ProductInfo.UnitPrice" placeholder="unit price" step="0.01" 
                min="0.00" />
        <span asp-validation-for="ProductInfo.UnitPrice"></span>
    </label>
    <label>
        Units On Order:
        <input type="text" asp-for="ProductInfo.UnitsOnOrder" placeholder="units on order" disabled="true"/>
        <span asp-validation-for="ProductInfo.UnitsOnOrder"></span>
    </label>
    @* for a checkbox, the transfer of data by default is either: not checked -> null, checked -> on
        IF you are expecting a boolean (true or false) then use the attribute value="true"
            this will result in: not checked -> null, checked -> true
        Why does this work? REMEMBER: when an instance is created, the properties in your instance
            will be set to: a) system defaults depending on datatype or b) constructor assignments.
            THEREFORE the default of a boolean property will be "false"
    *@
    <label>
        Discontinued:
        <input type="checkbox" asp-for="ProductInfo.Discontinued" value="true" />
        <span asp-validation-for="ProductInfo.Discontinued"></span>
    </label>
    <br/><br/>

    @* Managing the buttons, restricting user access*@
    @if (Model.ProductInfo != null)
    {
        <button type="submit" asp-page-handler="New" disabled>Save New</button>
        <button type="submit" asp-page-handler="Update">Update</button>
        @* add Javascript prompt for delete confirmation using the onclick *@
        <button type="submit" asp-page-handler="Delete" formnovalidate
                onclick="return confirm('Are you sure you wish to discontinue the product?')">
            Discontinue
        </button>
        <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
        <button type="submit" asp-page-handler="Search" formnovalidate>Search</button>
    }
    else
    {
    <button type="submit" asp-page-handler="New">Save New</button>
    <button type="submit" asp-page-handler="Update" disabled>Update</button>
    @* add Javascript prompt for delete confirmation using the onclick *@
    <button type="submit" asp-page-handler="Delete" formnovalidate disabled
            onclick="return confirm('Are you sure you wish to discontinue the product?')">
        Discontinue
    </button>
    <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
    <button type="submit" asp-page-handler="Search" formnovalidate>Search</button>
    }
</form>